apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  activeDeadlineSeconds: 180
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: {{ .Values.containerImage }}
        imagePullPolicy: Never
        env:
{{ include "eventhub.global.env" . | indent 8 }}
        - name: "ConnectionStrings__Default"
          value: {{ .Values.global.defaultConnString }}
      restartPolicy: Never
  backoffLimit: 10